USE bachEndDatabase;

INSERT INTO school_rankings (schoolName, ranking) VALUES
('Join University', 1),
('Berklee College of Music', 2),
('Juilliard School of Music', 3),
('Curtis Institute of Music', 4),
('Royal Conservatory of Melody', 5),
('Manhattan School of Music', 6),
('New Orleans Jazz Conservatory', 7),
('Vienna Academy of Piano Arts', 8),
('Guildhall School of Music Theory', 9),
('Tokyo Electronic Music Institute', 10),
('Dublin School of Folk Arts', 11),
('Chicago School of Improvisation', 12),
('Nashville Guitar Institute', 13),
('Cambridge Choral Academy', 14),
('London Royal Symphony College', 15),
('Berlin Keyboard Conservatory', 16),
('Seattle Bass Performance School', 17),
('Paris Violin Conservatoire', 18),
('Florence Cello Academy', 19),
('New York Trumpet Conservatory', 20),
('Lisbon Flute Institute', 21),
('Madrid Oboe Academy', 22),
('Prague Clarinet Conservatory', 23),
('Los Angeles Drum Academy', 24),
('Buenos Aires Accordion Institute', 25),
('Rome Mandolin Academy', 26),
('Chicago Tuba Conservatory', 27),
('Honolulu Ukulele Institute', 28),
('Edinburgh Bagpipe Academy', 29),
('Mexico City Marimba Conservatory', 30),
('Sydney Xylophone School', 31),
('Mumbai Tabla Institute', 32),
('Austin Harmonica Conservatory', 33),
('Oslo Electric Violin Academy', 34),
('Toronto Voice Arts School', 35),
('San Francisco Synth Academy', 36),
('Berlin Music Production Lab', 37),
('New Orleans Big Band Conservatory', 38),
('Boston Chamber Ensemble Institute', 39),
('Chicago Jazz Club Academy', 40);
