use bachEndDatabase;

insert into clubs (name, category, location, description) values
('chamber ensemble', 'performance', 101, 'A group focused on chamber music, exploring small ensemble repertoire.'),
('jazz club', 'performance', 102, 'All jazz lovers welcome, from beginner improvisers to advanced musicians.'),
('rock band', 'casual', 101, 'Students who enjoy playing rock music and forming bands.'),
('vocal ensemble', 'academic', 103, 'Choral group performing classical and contemporary works.'),
('piano society', 'academic', 104, 'Club for piano enthusiasts to practice and perform.'),
('strings club', 'performance', 105, 'Focus on string instruments: violin, viola, cello, and bass.'),
('wind instruments guild', 'academic', 106, 'For woodwind and brass players to share techniques.'),
('percussion circle', 'casual', 107, 'Hands-on group for percussionists of all skill levels.'),
('music theory society', 'academic', 108, 'Club for discussing music theory, harmony, and analysis.'),
('electronic music collective', 'performance', 109, 'Students producing and performing electronic music.'),
('composition workshop', 'academic', 110, 'Collaborative environment for aspiring composers.'),
('improv ensemble', 'performance', 111, 'Experimental improvisation group for all instruments.'),
('choir', 'performance', 112, 'Vocal ensemble performing choral repertoire.'),
('orchestra', 'performance', 113, 'Full symphony orchestra open to all students.'),
('big band', 'performance', 114, 'Jazz big band performing swing, blues, and modern arrangements.'),
('folk music club', 'casual', 115, 'Club exploring traditional and modern folk music.'),
('latin percussion ensemble', 'performance', 116, 'Specializes in Latin American percussion music.'),
('synthesizer club', 'academic', 117, 'Learn synthesis and electronic instrument design.'),
('guitar ensemble', 'performance', 118, 'Acoustic and electric guitar ensemble performing multiple styles.'),
('violin society', 'academic', 119, 'Focus on violin technique, repertoire, and performance.'),
('cello collective', 'performance', 120, 'Collaborative cello group performing solos and ensembles.'),
('trumpet club', 'academic', 121, 'Trumpet players meet to practice and perform.'),
('flute guild', 'academic', 122, 'Flutists collaborate, perform, and share techniques.'),
('oboe ensemble', 'academic', 123, 'Chamber music group focused on oboe repertoire.'),
('clarinet society', 'academic', 124, 'Club for clarinet players to practice and learn together.'),
('drum circle', 'casual', 125, 'Open drum circle for rhythmic exploration and fun.'),
('accordion society', 'performance', 126, 'Accordion players performing various styles.'),
('mandolin club', 'performance', 127, 'Mandolin ensemble and solo performances.'),
('tuba ensemble', 'academic', 128, 'Focus on tuba techniques and ensemble work.'),
('bass guitar guild', 'casual', 129, 'Bass guitar enthusiasts practicing and jamming together.'),
('keyboard collective', 'academic', 130, 'Keyboard players collaborating on classical and modern works.'),
('ukulele club', 'casual', 131, 'Fun and informal ukulele jam sessions.'),
('bagpipes society', 'performance', 132, 'Performance group specializing in bagpipe music.'),
('marimba ensemble', 'performance', 133, 'Percussion ensemble focusing on marimba repertoire.'),
('xylophone club', 'casual', 134, 'Informal group practicing xylophone techniques and music.'),
('tabla collective', 'performance', 135, 'Indian percussion ensemble exploring rhythms and compositions.'),
('harmonica guild', 'casual', 136, 'All levels welcome to practice and perform harmonica music.'),
('electric violin club', 'academic', 137, 'Explore modern and amplified violin techniques.'),
('voice masterclass', 'academic', 138, 'Workshops and performances for vocal students.'),
('music production lab', 'academic', 139, 'Students learning recording, mixing, and production techniques.'),
('experimental ensemble', 'performance', 140, 'Group experimenting with new sounds, instruments, and compositions.');