USE bachEndDatabase;

insert into club_members (studentId, clubName, role) values
(1, 'chamber ensemble', 'member'),
(151, 'jazz club', 'member'),
(152, 'rock band', 'member'),
(153, 'vocal ensemble', 'member'),
(154, 'piano society', 'member'),
(155, 'strings club', 'member'),
(156, 'wind instruments guild', 'member'),
(157, 'percussion circle', 'member'),
(158, 'music theory society', 'member'),
(159, 'electronic music collective', 'member'),
(160, 'composition workshop', 'member'),
(161, 'improv ensemble', 'member'),
(162, 'choir', 'member'),
(163, 'orchestra', 'member'),
(164, 'big band', 'member'),
(165, 'folk music club', 'member'),
(166, 'latin percussion ensemble', 'member'),
(167, 'synthesizer club', 'member'),
(168, 'guitar ensemble', 'member'),
(169, 'violin society', 'member'),
(150, 'cello collective', 'member'),
(151, 'trumpet club', 'member'),
(152, 'flute guild', 'member'),
(153, 'oboe ensemble', 'member'),
(154, 'clarinet society', 'member'),
(155, 'drum circle', 'member'),
(156, 'accordion society', 'member'),
(157, 'mandolin club', 'member'),
(158, 'tuba ensemble', 'member'),
(159, 'bass guitar guild', 'member'),
(160, 'keyboard collective', 'member'),
(161, 'ukulele club', 'member'),
(162, 'bagpipes society', 'member'),
(163, 'marimba ensemble', 'member'),
(164, 'xylophone club', 'member'),
(165, 'tabla collective', 'member'),
(166, 'harmonica guild', 'member'),
(167, 'electric violin club', 'member'),
(168, 'voice masterclass', 'member'),
(169, 'music production lab', 'member');

insert into club_members (studentId, clubName, role) values

(202, 'chamber ensemble', 'member'),
(203, 'jazz club', 'member'),
(204, 'rock band', 'member'),
(205, 'vocal ensemble', 'member'),
(206, 'piano society', 'member'),
(207, 'strings club', 'member'),
(208, 'wind instruments guild', 'member'),
(209, 'percussion circle', 'member'),
(210, 'music theory society', 'member'),
(211, 'electronic music collective', 'member'),
(212, 'composition workshop', 'member'),
(213, 'improv ensemble', 'member'),
(214, 'choir', 'member'),
(215, 'orchestra', 'member'),
(216, 'big band', 'member'),
(217, 'folk music club', 'member'),
(218, 'latin percussion ensemble', 'member'),
(219, 'synthesizer club', 'member'),
(220, 'guitar ensemble', 'member'),
(221, 'violin society', 'member'),
(222, 'cello collective', 'member'),
(223, 'trumpet club', 'member'),
(224, 'flute guild', 'member'),
(225, 'oboe ensemble', 'member'),
(226, 'clarinet society', 'member'),
(227, 'drum circle', 'member'),
(228, 'accordion society', 'member'),
(229, 'mandolin club', 'member'),
(230, 'tuba ensemble', 'member'),
(231, 'bass guitar guild', 'member'),
(232, 'keyboard collective', 'member'),
(233, 'ukulele club', 'member'),
(234, 'bagpipes society', 'member'),
(235, 'marimba ensemble', 'member'),
(236, 'xylophone club', 'member'),
(237, 'tabla collective', 'member'),
(238, 'harmonica guild', 'member'),
(239, 'electric violin club', 'member'),
(240, 'voice masterclass', 'member'),
(241, 'music production lab', 'member');

