USE bachEndDatabase;

insert into maintenance_request_tools (orderId, tool) values
(1, 'Hammer'),
(2, 'Screwdriver Set'),
(3, 'Wrench'),
(4, 'Pliers'),
(5, 'Drill'),
(6, 'Tape Measure'),
(7, 'Saw'),
(8, 'Level'),
(9, 'Glue Gun'),
(10, 'Sandpaper Pack'),
(11, 'Hammer'),
(12, 'Screwdriver Set'),
(13, 'Wrench'),
(14, 'Pliers'),
(15, 'Drill'),
(16, 'Tape Measure'),
(17, 'Saw'),
(18, 'Level'),
(19, 'Glue Gun'),
(20, 'Sandpaper Pack'),
(21, 'Hammer'),
(22, 'Screwdriver Set'),
(23, 'Wrench'),
(24, 'Pliers'),
(25, 'Drill'),
(26, 'Tape Measure'),
(27, 'Saw'),
(28, 'Level'),
(29, 'Glue Gun'),
(30, 'Sandpaper Pack'),
(31, 'Hammer'),
(32, 'Screwdriver Set'),
(33, 'Vice'),
(34, 'Pliers'),
(35, 'Drill'),
(36, 'Vice'),
(37, 'Saw'),
(38, 'Wire Stripper'),
(39, 'Vice'),
(39, 'Wire Stripper');
