USE bachEndDatabase;

insert into maintenance_request_tools (orderId, tool) values
(1, 'hammer'),
(2, 'screwdriver'),
(3, 'wrench'),
(4, 'pliers'),
(5, 'drill'),
(6, 'tape measure'),
(7, 'saw'),
(8, 'level'),
(9, 'glue gun'),
(10, 'sandpaper'),
(11, 'hammer'),
(12, 'screwdriver'),
(13, 'wrench'),
(14, 'pliers'),
(15, 'drill'),
(16, 'tape measure'),
(17, 'saw'),
(18, 'level'),
(19, 'glue gun'),
(20, 'sandpaper'),
(21, 'hammer'),
(22, 'screwdriver'),
(23, 'wrench'),
(24, 'pliers'),
(25, 'drill'),
(26, 'tape measure'),
(27, 'saw'),
(28, 'level'),
(29, 'glue gun'),
(30, 'sandpaper'),
(31, 'hammer'),
(32, 'screwdriver'),
(33, 'wrench'),
(34, 'pliers'),
(35, 'drill'),
(36, 'tape measure'),
(37, 'saw'),
(38, 'level'),
(39, 'glue gun'),
(40, 'sandpaper');
