USE bachEndDatabase;

INSERT INTO course_donations (donorName, amount, donatedAt, courseId, note) VALUES
('Acme Arts Foundation',       150000.00, DATE_SUB(CURDATE(), INTERVAL 90 DAY),   11, 'Annual grant — Advanced Composition'),
('Golden Stage Trust',           85000.00, DATE_SUB(CURDATE(), INTERVAL 45 DAY),   12, 'Lighting upgrade — Jazz History'),
('Velocity Media LLC',           40000.00, DATE_SUB(CURDATE(), INTERVAL 20 DAY),   33, 'Scholarship fund — Advanced Production'),
('Harmony Philanthropy',         60000.00, DATE_SUB(CURDATE(), INTERVAL 15 DAY),   14, 'Choir sheet music sponsorship'),
('City Cultural Council',       100000.00, DATE_SUB(CURDATE(), INTERVAL 120 DAY),   5, 'Community outreach funding — Piano Mastery'),
('StageCraft Supplies Co.',      25000.00, DATE_SUB(CURDATE(), INTERVAL 75 DAY),   46, 'Set design materials'),
('Global Arts Network',          92000.00, DATE_SUB(CURDATE(), INTERVAL 200 DAY),  30, 'Electronic Composition lab upgrade'),
('Fine Arts Alumni Assoc.',      55000.00, DATE_SUB(CURDATE(), INTERVAL 5 DAY),    42, 'Student travel scholarships'),
('Blue Note Records',            72000.00, DATE_SUB(CURDATE(), INTERVAL 33 DAY),   21, 'Jazz ensemble recording session'),
('National Endowment for Arts', 130000.00, DATE_SUB(CURDATE(), INTERVAL 150 DAY),  19, 'Contemporary Dance Program grant'),
('Visionary Voices Fund',        48000.00, DATE_SUB(CURDATE(), INTERVAL 12 DAY),    9, 'Guest lecture series — Music Theory'),
('Performance Partners LLC',     38000.00, DATE_SUB(CURDATE(), INTERVAL 60 DAY),   44, 'Stage lighting renovation'),
('Artisans Guild',               27000.00, DATE_SUB(CURDATE(), INTERVAL 48 DAY),   16, 'Costume design competition support'),
('Symphony Supporters',          88000.00, DATE_SUB(CURDATE(), INTERVAL 210 DAY),  15, 'Orchestral expansion fund'),
('Campus Cultural Collective',   51000.00, DATE_SUB(CURDATE(), INTERVAL 25 DAY),   25, 'Student art gallery exhibit'),
('Old Town Music Society',       45000.00, DATE_SUB(CURDATE(), INTERVAL 400 DAY),   5, 'Legacy piano restoration'),
('Global Stage Alliance',        79000.00, DATE_SUB(CURDATE(), INTERVAL 365 DAY),  14, 'International choir festival'),
('Historic Arts Foundation',     61000.00, DATE_SUB(CURDATE(), INTERVAL 330 DAY),  33, 'Archival digitization project'),
('Dance Heritage Council',       58000.00, DATE_SUB(CURDATE(), INTERVAL 310 DAY),  19, 'Historic dance costume preservation'),
('Citywide Cultural Fund',       99000.00, DATE_SUB(CURDATE(), INTERVAL 280 DAY),  30, 'Urban arts community program'),
('Classical Strings Society',    82000.00, DATE_SUB(CURDATE(), INTERVAL 260 DAY),  15, 'String instrument maintenance'),
('Digital Arts Trust',           55000.00, DATE_SUB(CURDATE(), INTERVAL 240 DAY),  42, 'VR performance lab equipment');

INSERT INTO course_expenses (amount, spentAt, courseId, category, memo) VALUES
(120000.00, DATE_SUB(CURDATE(), INTERVAL 80 DAY),   5,  'Salaries',   'Adjuncts — Piano Mastery'),
( 65000.00, DATE_SUB(CURDATE(), INTERVAL 60 DAY),  14,  'Equipment',  'Flooring — Choir Ensemble'),
( 42000.00, DATE_SUB(CURDATE(), INTERVAL 30 DAY),  30,  'Supplies',   'Studios — Electronic Composition'),
( 55000.00, DATE_SUB(CURDATE(), INTERVAL 10 DAY),  46,  'Production', 'Costumes — Brass Quintet'),
( 38000.00, DATE_SUB(CURDATE(), INTERVAL 12 DAY),  42,  'Travel',     'Competition travel — Student orchestra'),
( 27500.00, DATE_SUB(CURDATE(), INTERVAL 5 DAY),   21,  'Recording',  'Jazz ensemble studio rental'),
( 95000.00, DATE_SUB(CURDATE(), INTERVAL 45 DAY),  19,  'Renovation', 'Dance studio floor replacement'),
( 33000.00, DATE_SUB(CURDATE(), INTERVAL 25 DAY),   9,  'Hospitality','Guest lecturer accommodation'),
( 61000.00, DATE_SUB(CURDATE(), INTERVAL 70 DAY),  44,  'Lighting',   'New LED fixtures for theater'),
( 48000.00, DATE_SUB(CURDATE(), INTERVAL 40 DAY),  16,  'Materials',  'Fabric and sewing machines for costume class'),
( 83000.00, DATE_SUB(CURDATE(), INTERVAL 95 DAY),  15,  'Instruments','Purchase of new violins and cellos'),
( 24000.00, DATE_SUB(CURDATE(), INTERVAL 18 DAY),  25,  'Exhibit',    'Installation of art gallery displays'),
( 51500.00, DATE_SUB(CURDATE(), INTERVAL 150 DAY), 11,  'Printing',   'Advanced Composition coursebooks'),
( 45200.00, DATE_SUB(CURDATE(), INTERVAL 55 DAY),  12,  'Sound',      'PA system for Jazz History lecture hall'),
( 36000.00, DATE_SUB(CURDATE(), INTERVAL 85 DAY),  33,  'Lab',        'Electronic Production software licenses'),
( 41500.00, DATE_SUB(CURDATE(), INTERVAL 400 DAY),  5,  'Restoration','Piano refinishing project'),
( 37800.00, DATE_SUB(CURDATE(), INTERVAL 365 DAY), 14,  'Festival',   'Choir festival travel'),
( 29000.00, DATE_SUB(CURDATE(), INTERVAL 330 DAY), 33,  'Archiving',  'Media digitization equipment'),
( 50200.00, DATE_SUB(CURDATE(), INTERVAL 310 DAY), 19,  'Preservation','Dance costume restoration'),
( 63500.00, DATE_SUB(CURDATE(), INTERVAL 280 DAY), 30,  'Community',  'Urban arts outreach materials'),
( 72000.00, DATE_SUB(CURDATE(), INTERVAL 260 DAY), 15,  'Repair',     'Cello and violin restoration'),
( 41500.00, DATE_SUB(CURDATE(), INTERVAL 240 DAY), 42,  'Technology', 'VR lab installation and calibration'),
(58000.00, DATE_SUB(CURDATE(), INTERVAL 75 DAY),  1, 'Equipment',  'Studio mics — Intro to Composition'),
(46000.00, DATE_SUB(CURDATE(), INTERVAL 48 DAY), 11, 'Supplies',   'Notation software — Advanced Composition'),
(72000.00, DATE_SUB(CURDATE(), INTERVAL 22 DAY), 21, 'Salaries',   'Guest ensemble — Chamber Music'),
(39000.00, DATE_SUB(CURDATE(), INTERVAL 6 DAY),  31, 'Production', 'Recording session — Orchestration');
