insert into instruments (name, isAvailable, type) values
('Piano', true, 'keyboard'),
('Guitar', true, 'string'),
('Violin', false, 'string'),
('Drums', true, 'percussion'),
('Saxophone', true, 'wind'),
('Flute', true, 'wind'),
('Trumpet', false, 'wind'),
('Cello', true, 'string'),
('Clarinet', true, 'wind'),
('Trombone', false, 'wind'),
('Bass Guitar', true, 'string'),
('Electric Keyboard', true, 'keyboard'),
('Oboe', true, 'wind'),
('Harp', false, 'string'),
('Accordion', true, 'keyboard'),
('Mandolin', true, 'string'),
('Tuba', true, 'wind'),
('Percussion Set', false, 'percussion'),
('Synthesizer', true, 'keyboard'),
('Viola', true, 'string'),
('Double Bass', true, 'string'),
('French Horn', false, 'wind'),
('Congas', true, 'percussion'),
('Bongos', true, 'percussion'),
('Recorder', true, 'wind'),
('Electric Guitar', true, 'string'),
('Tambourine', true, 'percussion'),
('Sitar', true, 'string'),
('Harmonica', true, 'wind'),
('Piccolo', false, 'wind'),
('Marimba', true, 'percussion'),
('Xylophone', true, 'percussion'),
('Synth Pad', true, 'keyboard'),
('Banjo', true, 'string'),
('Bassoon', true, 'wind'),
('Electric Violin', true, 'string'),
('Tabla', true, 'percussion'),
('Ukulele', true, 'string'),
('Bagpipes', true, 'wind');
