insert into school_rankings (schoolName, ranking) values
('college of composition', 1),
('college of jazz', 2),
('college of production', 3),
('college of strings', 4),
('college of percussion', 5),
('college of vocals', 6),
('college of winds', 7),
('college of piano', 8),
('college of theory', 9),
('college of electronic music', 10),
('college of folk music', 11),
('college of improvisation', 12),
('college of guitar', 13),
('college of choir', 14),
('college of orchestra', 15),
('college of keyboard', 16),
('college of bass', 17),
('college of violin', 18),
('college of cello', 19),
('college of trumpet', 20),
('college of flute', 21),
('college of oboe', 22),
('college of clarinet', 23),
('college of drum', 24),
('college of accordion', 25),
('college of mandolin', 26),
('college of tuba', 27),
('college of ukulele', 28),
('college of bagpipes', 29),
('college of marimba', 30),
('college of xylophone', 31),
('college of tabla', 32),
('college of harmonica', 33),
('college of electric violin', 34),
('college of voice', 35),
('college of synth', 36),
('college of music production lab', 37),
('college of big band', 38),
('college of chamber ensemble', 39),
('college of jazz club', 40);
