insert into tools (productName, amount) values
('Screwdriver', 15),
('Hammer', 10),
('Wrench', 8),
('Drill', 5),
('Pliers', 12),
('Tape Measure', 20),
('Saw', 4),
('Chisel', 6),
('Sanding Paper', 25),
('Glue Gun', 10),
('Multimeter', 5),
('Level', 7),
('Clamps', 10),
('Files', 12),
('Soldering Iron', 8),
('Wire Cutters', 15),
('Stapler', 10),
('Hand Drill', 6),
('Crowbar', 3),
('Hex Key Set', 10),
('Paint Brush', 20),
('Utility Knife', 10),
('Measuring Tape', 15),
('Socket Set', 7),
('Allen Wrench', 12),
('Chalk Line', 5),
('Vice', 3),
('Ruler', 15),
('Clamp', 8),
('Glue Stick', 25),
('Paint Roller', 10),
('Wire Stripper', 6),
('Level Tool', 8),
('Screwdriver Set', 12),
('Sandpaper Pack', 15),
('Workbench', 2),
('C-Clamp', 7),
('Toolbox', 5),
('Electric Sander', 4);
